# Generated by Django 3.2 on 2021-07-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_finalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='finalprice',
            field=models.IntegerField(blank=True),
        ),
    ]
