# Generated by Django 3.2 on 2021-07-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_finalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='finalprice',
        ),
    ]
