# Generated by Django 3.2 on 2021-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_finalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finalprice',
            field=models.IntegerField(default=0),
        ),
    ]
