# Generated by Django 3.2 on 2021-07-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_finalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='pics/profile'),
        ),
    ]
