# Generated by Django 3.2 on 2021-06-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210608_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='usr_ph_otp',
        ),
        migrations.AlterField(
            model_name='otp',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
