# Generated by Django 3.2 on 2021-07-01 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('price', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Canceled', 'Canceled'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='PLACED', max_length=50)),
                ('pay_method', models.CharField(default='COD', max_length=100)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
