# Generated by Django 3.2 on 2021-07-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
