# Generated by Django 3.2 on 2021-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20210701_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
