# Generated by Django 3.2 on 2021-07-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/profile'),
        ),
    ]
